apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: credentials-sync
  namespace: flux-system
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: mcr.microsoft.com/azure-cli
            env:
            - name: RECONCILE_SH
              value: |-
                reconcile() {
                  echo "Starting ACR token sync -- $(date)"
                  echo "Logging into Azure"
                  az login --identity
                  echo "Logging into ACR: ${ACR_NAME}"
                  output="$(az acr login --expose-token -o=tsv -n "${ACR_NAME}")"
                  read token server <<< "${output}"
                  user="00000000-0000-0000-0000-000000000000"

                  apply-secret "${KUBE_SECRET}" "${token}" "${user}" "${server}"

                  echo "Finished ACR token sync -- $(date)"
                  echo
                }
