apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/fluxcd/kustomize-controller/config//crd?ref=v0.0.6
- github.com/fluxcd/kustomize-controller/config//manager?ref=v0.0.6
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kustomize-controller
  path: patch.yaml
