apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/kustomize-controller/releases/download/v0.12.0/kustomize-controller.crds.yaml
- https://github.com/fluxcd/kustomize-controller/releases/download/v0.12.0/kustomize-controller.deployment.yaml
- account.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kustomize-controller
  path: patch.yaml
