apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/fluxcd/source-controller/config//crd?ref=v0.0.1-alpha.3
- github.com/fluxcd/source-controller/config//manager?ref=v0.0.1-alpha.3
