apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/fluxcd/source-controller/config//crd?ref=v0.0.16
- github.com/fluxcd/source-controller/config//manager?ref=v0.0.16
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: source-controller
  path: patch.yaml
