apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/source-controller/archive/v0.7.2.zip//source-controller-0.7.2/config/crd
- https://github.com/fluxcd/source-controller/archive/v0.7.2.zip//source-controller-0.7.2/config/manager
- account.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: source-controller
  path: patch.yaml
