builds:
  - main: ./cmd/gotk
    ldflags:
      - -s -w -X main.VERSION={{ .Version }}
    binary: gotk
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
brews:
  - name: gotk
    tap:
      owner: fluxcd
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://toolkit.fluxcd.io/"
    description: "GitOps Toolkit CLI"
    dependencies:
      - name: kubectl
        type: optional
    test: |
      system "#{bin}/gotk --version"
