builds:
  - main: ./cmd/tk
    ldflags:
      - -s -w -X main.VERSION={{ .Version }}
    binary: tk
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
