site_name: GitOps Toolkit
site_description: A toolkit for assembling GitOps pipelines on Kubernetes
site_author: The Flux CD contributors
site_url: https://toolkit.fluxcd.io

repo_name: fluxcd/toolkit
repo_url: https://github.com/fluxcd/toolkit
edit_uri: ""

theme:
  name: material
  logo: _files/flux-icon@2x.png
  language: en
  palette:
    primary: blue
    accent: indigo
  custom_dir: mkdocs/

docs_dir: docs

extra_css:
  - _static/custom.css

plugins:
  - search

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      highlight_code: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: index.md
  - Get Started: get-started/index.md
  - Guides:
      - Installation: guides/installation.md
      - Manage Helm Releases: guides/helmreleases.md
      - Setup Notifications: guides/notifications.md
      - Setup Webhook Receivers: guides/webhook-receivers.md
      - Sealed Secrets: guides/sealed-secrets.md
      - Mozilla SOPS: guides/mozilla-sops.md
  - Toolkit Components:
    - Source Controller:
      - Overview: components/source/controller.md
      - GitRepository CRD: components/source/gitrepositories.md
      - HelmRepository CRD: components/source/helmrepositories.md
      - HelmChart CRD: components/source/helmcharts.md
      - Source API Reference: components/source/api.md
    - Kustomize Controller:
      - Overview: components/kustomize/controller.md
      - Kustomization CRD: components/kustomize/kustomization.md
      - Kustomize API Reference: components/kustomize/api.md
    - Helm Controller:
        - Overview: components/helm/controller.md
        - HelmRelease CRD: components/helm/helmreleases.md
        - Helm API Reference: components/helm/api.md
    - Notification Controller:
        - Overview: components/notification/controller.md
        - Event: components/notification/event.md
        - Provider CRD: components/notification/provider.md
        - Alert CRD: components/notification/alert.md
        - Receiver CRD: components/notification/receiver.md
        - Notification API Reference: components/notification/api.md
  - Toolkit CLI:
    - Overview: cmd/gotk.md
    - Bootstrap: cmd/gotk_bootstrap.md
    - Bootstrap github: cmd/gotk_bootstrap_github.md
    - Bootstrap gitlab: cmd/gotk_bootstrap_gitlab.md
    - Check: cmd/gotk_check.md
    - Create: cmd/gotk_create.md
    - Create kustomization: cmd/gotk_create_kustomization.md
    - Create helmrelease: cmd/gotk_create_helmrelease.md
    - Create source: cmd/gotk_create_source.md
    - Create source git: cmd/gotk_create_source_git.md
    - Create source helm: cmd/gotk_create_source_helm.md
    - Create tenant: cmd/gotk_create_tenant.md
    - Delete: cmd/gotk_delete.md
    - Delete kustomization: cmd/gotk_delete_kustomization.md
    - Delete helmrelease: cmd/gotk_delete_helmrelease.md
    - Delete source: cmd/gotk_delete_source.md
    - Delete source git: cmd/gotk_delete_source_git.md
    - Delete source helm: cmd/gotk_delete_source_helm.md
    - Export: cmd/gotk_export.md
    - Export kustomization: cmd/gotk_export_kustomization.md
    - Export helmrelease: cmd/gotk_export_helmrelease.md
    - Export source: cmd/gotk_export_source.md
    - Export source git: cmd/gotk_export_source_git.md
    - Export source helm: cmd/gotk_export_source_helm.md
    - Get: cmd/gotk_get.md
    - Get kustomizations: cmd/gotk_get_kustomizations.md
    - Get helmreleases: cmd/gotk_get_helmreleases.md
    - Get sources: cmd/gotk_get_sources.md
    - Get sources git: cmd/gotk_get_sources_git.md
    - Get sources helm: cmd/gotk_get_sources_helm.md
    - Install: cmd/gotk_install.md
    - Resume: cmd/gotk_resume.md
    - Resume kustomization: cmd/gotk_resume_kustomization.md
    - Resume helmrelease: cmd/gotk_resume_helmrelease.md
    - Suspend: cmd/gotk_suspend.md
    - Suspend kustomization: cmd/gotk_suspend_kustomization.md
    - Suspend helmrelease: cmd/gotk_suspend_helmrelease.md
    - Reconcile: cmd/gotk_reconcile.md
    - Reconcile kustomization: cmd/gotk_reconcile_kustomization.md
    - Reconcile helmrelease: cmd/gotk_reconcile_helmrelease.md
    - Reconcile source: cmd/gotk_reconcile_source.md
    - Reconcile source git: cmd/gotk_reconcile_source_git.md
    - Reconcile source helm: cmd/gotk_reconcile_source_helm.md
    - Uninstall: cmd/gotk_uninstall.md
  - Roadmap: roadmap/index.md
  - Contributing: contributing/index.md
  - Dev Guides:
      - Watching for source changes: dev-guides/source-watcher.md
  - FAQ: faq/index.md
