- op: add
  path: /spec/template/spec/containers/0/args/0
  value: --events-addr=http://notification-controller.flux-system.svc.cluster.local./
- op: add
  path: /spec/template/spec/serviceAccountName
  value: image-automation-controller
