apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/notification-controller/archive/v0.7.0.zip//notification-controller-0.7.0/config/crd
- https://github.com/fluxcd/notification-controller/archive/v0.7.0.zip//notification-controller-0.7.0/config/manager
- account.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: notification-controller
    path: patch.yaml
