apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotk-system
resources:
  - namespace.yaml
  - ../bases/source-controller
  - ../bases/kustomize-controller
  - ../bases/notification-controller
  - ../bases/helm-controller
  - ../rbac
  - ../policies
transformers:
  - labels.yaml
