apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: flux-system
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: prometheus
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
      version: 1
