apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: gitops-system
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: grafana
