apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: acr-
commonLabels:
  app: acr-credentials-sync

namespace: flux-system

bases:
- ../_base
resources:
- az-identity.yaml

patchesStrategicMerge:
- config-patches.yaml
- reconcile-patch.yaml

vars:
- name: AZ_IDENTITY_NAME
  objref:
    kind: AzureIdentity
    name: credentials-sync
    apiVersion: aadpodidentity.k8s.io/v1

configurations:
- kustomizeconfig.yaml
