# This is a stub resource patched by config-patches.yaml, so that all config is visible in one file
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: lab # if this is changed, also change in config-patches.yaml
  namespace: flux-system
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: lab
  namespace: flux-system
spec:
  azureIdentity: $(AZ_IDENTITY_NAME) # match the AzureIdentity name
  selector: $(AZ_IDENTITY_NAME) # match the AzureIdentity name
