apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - account.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: prometheus
    files:
      - prometheus.yml
