apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: credentials-sync-eventhub

resources:
  - sync.yaml

patchesStrategicMerge:
  - kubectl-patch.yaml

vars:
  - name: KUBE_SECRET
    objref:
      kind: ConfigMap
      name: credentials-sync-eventhub
      apiVersion: v1
    fieldref:
      fieldpath: data.KUBE_SECRET

configurations:
  - kustomizeconfig.yaml
